{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   age     sex     bmi  children smoker     region      charges\n",
      "0   19  female  27.900         0    yes  southwest  16884.92400\n",
      "1   18    male  33.770         1     no  southeast   1725.55230\n",
      "2   28    male  33.000         3     no  southeast   4449.46200\n",
      "3   33    male  22.705         0     no  northwest  21984.47061\n",
      "4   32    male  28.880         0     no  northwest   3866.85520 (1337, 7)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "df = pd.read_csv('dataset2.csv')\n",
    "\n",
    "print(df.head(), df.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      age     sex     bmi  children smoker     region      charges  \\\n",
      "0      19  female  27.900         0    yes  southwest  16884.92400   \n",
      "1      18    male  33.770         1     no  southeast   1725.55230   \n",
      "2      28    male  33.000         3     no  southeast   4449.46200   \n",
      "3      33    male  22.705         0     no  northwest  21984.47061   \n",
      "4      32    male  28.880         0     no  northwest   3866.85520   \n",
      "...   ...     ...     ...       ...    ...        ...          ...   \n",
      "1332   50    male  30.970         3     no  northwest  10600.54830   \n",
      "1333   18  female  31.920         0     no  northeast   2205.98080   \n",
      "1334   18  female  36.850         0     no  southeast   1629.83350   \n",
      "1335   21  female  25.800         0     no  southwest   2007.94500   \n",
      "1336   61  female  29.070         0    yes  northwest  29141.36030   \n",
      "\n",
      "      anorexie_severe  anorexie_moderée  surpoids  obésité_modéré  \\\n",
      "0               False             False      True           False   \n",
      "1               False             False     False            True   \n",
      "2               False             False     False            True   \n",
      "3               False             False     False           False   \n",
      "4               False             False      True           False   \n",
      "...               ...               ...       ...             ...   \n",
      "1332            False             False     False            True   \n",
      "1333            False             False     False            True   \n",
      "1334            False             False     False           False   \n",
      "1335            False             False      True           False   \n",
      "1336            False             False      True           False   \n",
      "\n",
      "      obésité_severe  \n",
      "0              False  \n",
      "1              False  \n",
      "2              False  \n",
      "3              False  \n",
      "4              False  \n",
      "...              ...  \n",
      "1332           False  \n",
      "1333           False  \n",
      "1334            True  \n",
      "1335           False  \n",
      "1336           False  \n",
      "\n",
      "[1337 rows x 12 columns]\n"
     ]
    }
   ],
   "source": [
    "df_encoded = df.copy()\n",
    "\n",
    "# Créez des colonnes pour les différentes catégories\n",
    "df_encoded['anorexie_severe'] = np.where((df['bmi'].between(0, 15.99)), True, False)\n",
    "df_encoded['anorexie_moderée'] = np.where((df['bmi'].between(16, 17)), True, False)\n",
    "df_encoded['surpoids'] = np.where((df['bmi'].between(25, 29.99)), True, False)\n",
    "df_encoded['obésité_modéré'] = np.where((df['bmi'].between(30, 34.9)), True, False)\n",
    "df_encoded['obésité_severe'] = np.where((df['bmi'].between(35, 53)), True, False)\n",
    "\n",
    "\n",
    "\n",
    "print(df_encoded)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "verif des dimensions X et Y\n",
      "      X (dataset sans la variable cible): (1337, 11)\n",
      "      Y (la variable cible) : (1337,)\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.compose import ColumnTransformer, make_column_transformer\n",
    "from sklearn.preprocessing import OneHotEncoder, StandardScaler, KBinsDiscretizer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.metrics import r2_score\n",
    "from sklearn.preprocessing import FunctionTransformer\n",
    "import math\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.impute import SimpleImputer\n",
    "\n",
    "\n",
    "# separation des features et de la variable cible\n",
    "X = df_encoded.drop('charges', axis=1)\n",
    "y = df_encoded['charges']\n",
    "\n",
    "\n",
    "\n",
    "print(f'''verif des dimensions X et Y\n",
    "      X (dataset sans la variable cible): {X.shape}\n",
    "      Y (la variable cible) : {y.shape}''')\n",
    "\n",
    "\n",
    "# # division du dataset en ensembles d'entraînement et de test\n",
    "# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "# print(f''' verif du split 80 20 \n",
    "# 80% du dataset : X train -> {X_train.shape}, Y train -> {y_train.shape}\n",
    "# 20% du dataset : X test -> {X_test.shape}, Y test -> {y_test.shape}''')\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, train_size=0.85, random_state=42, stratify=X['smoker'])\n",
    "\n",
    "# preprocessing avec standardisation et transformation des categories\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', StandardScaler(), ['age', 'bmi', 'children']),\n",
    "        ('cat', OneHotEncoder(), ['region', 'sex', 'smoker','obésité_severe','obésité_modéré','surpoids','anorexie_moderée','anorexie_severe']),\n",
    "    ]\n",
    ")\n",
    "\n",
    "\n",
    "# preprocessing avec standardisation et transformation des categories\n",
    "# preprocessor = ColumnTransformer(\n",
    "#     transformers=[\n",
    "#         ('num', StandardScaler(), ['age', 'bmi', 'children']),\n",
    "#         ('cat', OneHotEncoder(), ['region', 'sex', 'smoker'])\n",
    "#     ]\n",
    "# )\n",
    "\n",
    "# preprocessing = make_column_transformer(\n",
    "#     (OneHotEncoder(), ['bmi_category','region', 'sex', 'smoker']),\n",
    "#     (StandardScaler(), ['age', 'children'])\n",
    "# )\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.linear_model import SGDRegressor\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error\n",
    "\n",
    "# ... (votre code existant)\n",
    "\n",
    "# Modèle SGD Regressor\n",
    "sgd_regressor_model = SGDRegressor(random_state=42)\n",
    "\n",
    "# Pipeline pour le SGD Regressor\n",
    "sgd_regressor_pipeline = Pipeline([\n",
    "    ('preprocessor', preprocessor),\n",
    "    ('regressor', sgd_regressor_model)\n",
    "])\n",
    "\n",
    "\n",
    "# Entraînement du modèle SGD Regressor\n",
    "sgd_regressor_pipeline.fit(X_train, y_train)\n",
    "\n",
    "# Prédictions sur l'ensemble de test\n",
    "sgd_regressor_predictions = sgd_regressor_pipeline.predict(X_test)\n",
    "\n",
    "# new_data = pd.DataFrame({\n",
    "#     'age': [35, 40, 30, 60],  # Exemple d'âges\n",
    "#     'sex': ['female', 'male', 'female', 'female'],\n",
    "#     'bmi': [22.5, 30.0, 25.0, 47],\n",
    "#     'children': [1, 2, 0, 5],\n",
    "#     'smoker': ['no', 'yes', 'no', 'yes'],\n",
    "#     'region': ['southwest', 'northeast', 'southeast', 'southeast']\n",
    "# })\n",
    "\n",
    "\n",
    "\n",
    "# # Faire des prédictions avec le modèle optimisé\n",
    "# predictions = sgd_regressor_pipeline.predict(new_data)\n",
    "\n",
    "# # Ajouter les prédictions à votre DataFrame d'origine\n",
    "# new_data['predicted_charges'] = predictions\n",
    "\n",
    "# # Afficher le DataFrame avec les prédictions\n",
    "# print(new_data)\n",
    "\n",
    "# score = sgd_regressor_pipeline.score(X_train, y_train)\n",
    "# print(score)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.4299674302679001\n",
      "Mean Squared Error du modèle lasso: 73402583.67185716\n",
      "Coefficient of Determination R² du modèle: 0.4934811151027304\n",
      "Root Mean Squared Error (RMSE) du modèle: 8567.530780327384\n",
      "Meilleurs hyperparamètres: {'regressor__alpha': 1.0, 'regressor__l1_ratio': 0.3}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# AVEC LE Modele de regression ElasticNet\n",
    "\n",
    "\n",
    "from sklearn.linear_model import Lasso, Ridge\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import ElasticNet\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "\n",
    "# création du pipeline de prétraitement et du modèle elasticnet\n",
    "pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),\n",
    "                           ('regressor', ElasticNet())])\n",
    "\n",
    "\n",
    "#test de différents hyperparam d'alpha entre ridge et lasso \n",
    "param_grid_elasticnet = {\n",
    "    'regressor__alpha': [1.0, 2, 3, 4],\n",
    "    'regressor__l1_ratio': [0.3, 0.5, 0.7, 1]\n",
    "    }\n",
    "\n",
    "### grid search\n",
    "grid_elasticnet = GridSearchCV(pipeline_rf, param_grid_elasticnet, cv=5)\n",
    "\n",
    "\n",
    "# eviter data leakage -> entraîner le pipeline sur les données d'entraînement \n",
    "grid_elasticnet.fit(X_train, y_train)\n",
    "#puis predire y sur l'ensemble de test avec le meme pipeline\n",
    "y_pred = grid_elasticnet.predict(X_test)\n",
    "# print(y_pred)\n",
    "score = grid_elasticnet.score(X_train, y_train)\n",
    "print(score)\n",
    "#test des les differents metriques sur modele lasso\n",
    "#comparaison du y prédit avec le y de test\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "\n",
    "print(f'Mean Squared Error du modèle lasso: {mse}')\n",
    "\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(f'Coefficient of Determination R² du modèle: {r2}')\n",
    "\n",
    "rmse = math.sqrt(mse)\n",
    "print(f'Root Mean Squared Error (RMSE) du modèle: {rmse}')\n",
    "\n",
    "\n",
    "# Récupérer les meilleurs hyperparamètres\n",
    "best_params = grid_elasticnet.best_params_\n",
    "print(\"Meilleurs hyperparamètres:\", best_params)\n",
    "\n",
    "# Récupérer le modèle avec les meilleurs hyperparamètres\n",
    "best_model = grid_elasticnet.best_estimator_\n",
    "\n",
    "\n",
    "# new_data = pd.DataFrame({\n",
    "#     'age': [35, 40, 30, 60],  # Exemple d'âges\n",
    "#     'sex': ['female', 'male', 'female', 'female'],\n",
    "#     'bmi': [22.5, 30.0, 25.0, 47],\n",
    "#     'children': [1, 2, 0, 5],\n",
    "#     'smoker': ['no', 'yes', 'no', 'yes'],\n",
    "#     'region': ['southwest', 'northeast', 'southeast', 'southeast']\n",
    "# })\n",
    "\n",
    "\n",
    "# # Faire des prédictions avec le modèle optimisé\n",
    "# predictions = best_model.predict(new_data)\n",
    "\n",
    "# # Ajouter les prédictions à votre DataFrame d'origine\n",
    "# new_data['predicted_charges'] = predictions\n",
    "\n",
    "# # Afficher le DataFrame avec les prédictions\n",
    "# print(new_data)\n",
    "\n",
    "\n",
    "# # feature_names = preprocessor.get_feature_names_out()\n",
    "# # print(feature_names)\n",
    "\n",
    "\n",
    "\n",
    "# 0.6120666150641507\n",
    "# Mean Squared Error du modèle lasso: 60801052.43566085\n",
    "# Coefficient of Determination R² du modèle lasso: 0.669120838254013\n",
    "# Root Mean Squared Error (RMSE) du modèle lasso: 7797.502961567943\n",
    "# Meilleurs hyperparamètres: {'regressor__max_depth': 20, 'regressor__n_estimators': 200}\n",
    "#    age     sex   bmi  children smoker     region  predicted_charges\n",
    "# 0   35  female  22.5         1     no  southwest        8359.378446\n",
    "# 1   40    male  30.0         2    yes  northeast       30301.875435\n",
    "# 2   30  female  25.0         0     no  southeast        8670.986965\n",
    "# 3   60  female  47.0         5    yes  southeast       30971.347171\n",
    "\n",
    "\n",
    "# 0.9665290950043812\n",
    "# Mean Squared Error du modèle lasso: 21212643.285459656\n",
    "# Coefficient of Determination R² du modèle lasso: 0.884560853019168\n",
    "# Root Mean Squared Error (RMSE) du modèle lasso: 4605.7185417109085\n",
    "# Meilleurs hyperparamètres: {'regressor__max_depth': 10, 'regressor__n_estimators': 300}\n",
    "#    age     sex   bmi  children smoker     region  predicted_charges\n",
    "# 0   35  female  22.5         1     no  southwest        9254.140953\n",
    "# 1   40    male  30.0         2    yes  northeast       27878.313691\n",
    "# 2   30  female  25.0         0     no  southeast        4828.929915\n",
    "# 3   60  female  47.0         5    yes  southeast       48704.356252\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.160e+10, tolerance: 1.315e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.167e+10, tolerance: 1.298e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.437e+10, tolerance: 1.397e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.421e+10, tolerance: 1.381e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.007e+10, tolerance: 1.271e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.723e+10, tolerance: 1.315e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.701e+10, tolerance: 1.298e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.048e+10, tolerance: 1.397e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.009e+10, tolerance: 1.381e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.545e+10, tolerance: 1.271e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.962e+10, tolerance: 1.315e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.925e+10, tolerance: 1.298e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.310e+10, tolerance: 1.397e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.259e+10, tolerance: 1.381e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.773e+10, tolerance: 1.271e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.096e+10, tolerance: 1.315e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.050e+10, tolerance: 1.298e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.457e+10, tolerance: 1.397e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.400e+10, tolerance: 1.381e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.900e+10, tolerance: 1.271e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.557e+10, tolerance: 1.667e+07 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.\n",
      "  model = cd_fast.enet_coordinate_descent(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.35704489015216057\n",
      "Mean Squared Error du modèle lasso: 85114667.57783115\n",
      "Coefficient of Determination R² du modèle: 0.41266118502509597\n",
      "Root Mean Squared Error (RMSE) du modèle: 9225.761083934005\n",
      "Meilleurs hyperparamètres: {'regressor__alpha': 1.0, 'regressor__l1_ratio': 0}\n"
     ]
    }
   ],
   "source": [
    "# AVEC LE Modele de regression ElasticNet\n",
    "\n",
    "\n",
    "from sklearn.linear_model import Lasso, Ridge\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import ElasticNet\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "\n",
    "# création du pipeline de prétraitement et du modèle elasticnet\n",
    "pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),\n",
    "                           ('regressor', ElasticNet())])\n",
    "\n",
    "\n",
    "#test de différents hyperparam d'alpha ridge\n",
    "param_grid_elasticnet = {\n",
    "    'regressor__alpha': [1.0, 2, 3, 4],\n",
    "    'regressor__l1_ratio': [0]\n",
    "    }\n",
    "\n",
    "### grid search\n",
    "grid_elasticnet = GridSearchCV(pipeline_rf, param_grid_elasticnet, cv=5)\n",
    "\n",
    "\n",
    "# eviter data leakage -> entraîner le pipeline sur les données d'entraînement \n",
    "grid_elasticnet.fit(X_train, y_train)\n",
    "#puis predire y sur l'ensemble de test avec le meme pipeline\n",
    "y_pred = grid_elasticnet.predict(X_test)\n",
    "# print(y_pred)\n",
    "score = grid_elasticnet.score(X_train, y_train)\n",
    "print(score)\n",
    "#test des les differents metriques sur modele lasso\n",
    "#comparaison du y prédit avec le y de test\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "\n",
    "print(f'Mean Squared Error du modèle lasso: {mse}')\n",
    "\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(f'Coefficient of Determination R² du modèle: {r2}')\n",
    "\n",
    "rmse = math.sqrt(mse)\n",
    "print(f'Root Mean Squared Error (RMSE) du modèle: {rmse}')\n",
    "\n",
    "\n",
    "# Récupérer les meilleurs hyperparamètres\n",
    "best_params = grid_elasticnet.best_params_\n",
    "print(\"Meilleurs hyperparamètres:\", best_params)\n",
    "\n",
    "# Récupérer le modèle avec les meilleurs hyperparamètres\n",
    "best_model = grid_elasticnet.best_estimator_\n",
    "\n",
    "\n",
    "# new_data = pd.DataFrame({\n",
    "#     'age': [35, 40, 30, 60],  # Exemple d'âges\n",
    "#     'sex': ['female', 'male', 'female', 'female'],\n",
    "#     'bmi': [22.5, 30.0, 25.0, 47],\n",
    "#     'children': [1, 2, 0, 5],\n",
    "#     'smoker': ['no', 'yes', 'no', 'yes'],\n",
    "#     'region': ['southwest', 'northeast', 'southeast', 'southeast']\n",
    "# })\n",
    "\n",
    "\n",
    "# # Faire des prédictions avec le modèle optimisé\n",
    "# predictions = best_model.predict(new_data)\n",
    "\n",
    "# # Ajouter les prédictions à votre DataFrame d'origine\n",
    "# new_data['predicted_charges'] = predictions\n",
    "\n",
    "# # Afficher le DataFrame avec les prédictions\n",
    "# print(new_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 7 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:821: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 810, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py\", line 527, in __call__\n",
      "    return estimator.score(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 756, in score\n",
      "    Xt = transform.transform(Xt)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 827, in transform\n",
      "    Xs = self._fit_transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py\", line 681, in _fit_transform\n",
      "    return Parallel(n_jobs=self.n_jobs)(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/joblib/parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/pipeline.py\", line 940, in _transform_one\n",
      "    res = transformer.transform(X)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/utils/_set_output.py\", line 157, in wrapped\n",
      "    data_to_wrap = f(self, X, *args, **kwargs)\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 1027, in transform\n",
      "    X_int, X_mask = self._transform(\n",
      "  File \"/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py\", line 200, in _transform\n",
      "    raise ValueError(msg)\n",
      "ValueError: Found unknown categories [True] in column 6 during transform\n",
      "\n",
      "  warnings.warn(\n",
      "/home/utilisateur/Bureau/ML lib/ml/lib/python3.10/site-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.7432247902368283\n",
      "Mean Squared Error du modèle lasso: 25286199.947334982\n",
      "Coefficient of Determination R² du modèle: 0.8255110765872928\n",
      "Root Mean Squared Error (RMSE) du modèle: 5028.53854985074\n",
      "Meilleurs hyperparamètres: {'regressor__alpha': 1.0, 'regressor__l1_ratio': 1}\n"
     ]
    }
   ],
   "source": [
    "# AVEC LE Modele de regression ElasticNet\n",
    "\n",
    "\n",
    "from sklearn.linear_model import Lasso, Ridge\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import ElasticNet\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "\n",
    "# création du pipeline de prétraitement et du modèle elasticnet\n",
    "pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),\n",
    "                           ('regressor', ElasticNet())])\n",
    "\n",
    "\n",
    "#test de différents hyperparam d'alpha lasso\n",
    "param_grid_elasticnet = {\n",
    "    'regressor__alpha': [1.0, 2, 3, 4, 5, 6],\n",
    "    'regressor__l1_ratio': [1]\n",
    "    }\n",
    "\n",
    "### grid search\n",
    "grid_elasticnet = GridSearchCV(pipeline_rf, param_grid_elasticnet, cv=5)\n",
    "\n",
    "\n",
    "# eviter data leakage -> entraîner le pipeline sur les données d'entraînement \n",
    "grid_elasticnet.fit(X_train, y_train)\n",
    "#puis predire y sur l'ensemble de test avec le meme pipeline\n",
    "y_pred = grid_elasticnet.predict(X_test)\n",
    "# print(y_pred)\n",
    "score = grid_elasticnet.score(X_train, y_train)\n",
    "print(score)\n",
    "#test des les differents metriques sur modele lasso\n",
    "#comparaison du y prédit avec le y de test\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "\n",
    "print(f'Mean Squared Error du modèle lasso: {mse}')\n",
    "\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(f'Coefficient of Determination R² du modèle: {r2}')\n",
    "\n",
    "rmse = math.sqrt(mse)\n",
    "print(f'Root Mean Squared Error (RMSE) du modèle: {rmse}')\n",
    "\n",
    "\n",
    "# Récupérer les meilleurs hyperparamètres\n",
    "best_params = grid_elasticnet.best_params_\n",
    "print(\"Meilleurs hyperparamètres:\", best_params)\n",
    "\n",
    "# Récupérer le modèle avec les meilleurs hyperparamètres\n",
    "best_model = grid_elasticnet.best_estimator_\n",
    "\n",
    "\n",
    "# new_data = pd.DataFrame({\n",
    "#     'age': [35, 40, 30, 60],  # Exemple d'âges\n",
    "#     'sex': ['female', 'male', 'female', 'female'],\n",
    "#     'bmi': [22.5, 30.0, 25.0, 47],\n",
    "#     'children': [1, 2, 0, 5],\n",
    "#     'smoker': ['no', 'yes', 'no', 'yes'],\n",
    "#     'region': ['southwest', 'northeast', 'southeast', 'southeast']\n",
    "# })\n",
    "\n",
    "\n",
    "# # Faire des prédictions avec le modèle optimisé\n",
    "# predictions = best_model.predict(new_data)\n",
    "\n",
    "# # Ajouter les prédictions à votre DataFrame d'origine\n",
    "# new_data['predicted_charges'] = predictions\n",
    "\n",
    "# # Afficher le DataFrame avec les prédictions\n",
    "# print(new_data)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ml",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
